name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          awsUrl=244530008913.dkr.ecr.eu-west-1.amazonaws.com
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $awsUrl
          rev=$(git rev-parse --short HEAD)
          username=kaam004
          tag=pgr301kaam004eksamen
          docker build . -t $tag:$rev
          docker tag $tag:$rev $awsUrl/$username:$rev
          docker tag $tag:$rev $awsUrl/$username:latest
          docker push $awsUrl/$username:$rev
          docker push $awsUrl/$username:latest